---
title: "Extremalpinisten Forschungsbericht"
subtitle: "Hier kommt noch ein extrem spannender Subtitle hin"
author: "Dana Schneider, Luna Wolf, Tjorben Mattschull, Leah Haupenthal, Noa Siebert und Leonie Stieber"
date: "`r Sys.Date()`"
output: tint::tintHtml
---

```  {r setup, include=FALSE}
# @extremalpis: die Kommentare sind für uns alle, um uns hier zurechtzufinden 
# das hier ist unser setup - unsere Befehle, wie das Dokument afgebaut werden soll
library(igraph)
library(igraphdata)
library(knitr)
library(markdown)
library(tint)
```

# Gliederung 

1. Einleitung (worum geht es, ggf. Abstract, kleine theoretische Einordnung)
2. zentrale Leitfrage (und ggf. Hypothese)
3. Operationalisierung der Daten (Methodisches Vorgehen,genaue Darlegung der Datenerhebung usw.,Datenlage und Datenbereinigung)
4. Pretest
5. Analyse und Ergebnisse
6. Fazit, Learning und Diskussion 
7. Quellen
8. Anhang mit Arbeitsaufteilung

# 1. Einleitung 

(Frage an uns: Wollen wir unseren Bericht "interessant" oder "wissenschaftlich" schreiben?)

Die Szene rund um den Extremalpinismus hat im Jahr 2018 mit dem Dokumentarfilm "Free Solo" einen neuen Aufschwung an öffentlichem Interesse bekommen. 2019 wurde der Film mit dem Oskar zum "besten Dokumentarfilm" ausgezeichnet. 

Dennoch sind es meist nur kurze Ereignisse, die den Extremalpinimsus in die Gesellschaft integrieren, bevor er wieder von der Bildfläche verschwindet und nur die wirklichen Fans sich noch damit beschäftigen. Eines dieser Ereignisse ist die jährliche Verleihung des "Piolet d'Ors", der bedeutendsten Auszeichnung für außergewähnliche Leistungen im extremen Bergsport (Zitat). 

Lässt sich der Betrachter nach diesen kurzen Adrenalinstößen, die die Preisverliehungen auf diesem Gebiet zwangsläufig mit sich bringen dazu hinreißen, einen genaueren Blick auf die Akteure dieser Szene zu werfen, kommen Fragen auf, die in diesem Bericht ergründet werden wollen. 

(Beispielhafte Fragen: Bleiben die Extrembergsportler wenn Sie einmal angefangen haben in der Szene? Wie tödlich sind die Expeditionen? Gibt es ein Land aus dem die meisten Alpinisten kommen? Wie ist das durchschnittsalter? Wie ist das Verhältnis zwischen Männern und Frauen? Wie sieht es mit sozialen Kontkaten aus? ...) 



# 2. Zentrale Leitfrage und Hypothese

Der König hatte eine Tochter, die war sehr schön, aber sie war auch sehr wunderlich. Sie hatte das Gelübde gethan, keinen zum Herrn und Gemahl zu nehmen, der nicht verspräche, wenn sie zuerst stürbe, sich lebendig mit ihr begraben zu lassen. 'Hat er mich von Herzen lieb,' sagte sie, 'wozu dient ihm dann noch das Leben?' Dagegen wollte sie ein Gleiches thun, und wenn er zuerst stürbe, mit ihm in das Grab steigen. Dieses seltsame Gelübde hatte bis jetzt alle Freier abgeschreckt, aber der Jüngling wurde von ihrer Schönheit so eingenommen, daß er auf nichts achtete, sondern bei ihrem Vater um sie anhielt. 'Weißt du auch,' sprach der König, 'was du versprechen mußt?' 'Ich muß mit ihr in das Grab gehen,' antwortete er, 'wenn ich sie überlebe, aber meine Liebe ist so groß, daß ich der Gefahr nicht achte.' Da willigte der König ein, und die Hochzeit ward mit großer Pracht gefeiert.

# 3. Operationalisierung der Daten (Methodisches Vorgehen,genaue Darlegung der Datenerhebung usw.,Datenlage und Datenbereinigung)

Nun lebten sie eine Zeitlang glücklich und vergnügt mit einander, da geschah es, daß die junge Königin in eine schwere Krankheit fiel, und kein Arzt ihr helfen konnte. Und als sie todt da lag, da erinnerte sich der junge König was er hatte versprechen müssen, und es grauste ihm davor, sich lebendig in das Grab zu legen, aber es war kein Ausweg: der König hatte alle Thore mit Wachen besetzen lassen, und es war nicht möglich dem Schicksal zu entgehen. Als der Tag kam, wo die Leiche in das königliche Gewölbe beigesetzt wurde, da ward er mit hinabgeführt, und dann das Thor verriegelt und verschlossen.
Neben dem Sarg stand ein Tisch, darauf vier Lichter, vier Laibe Brot und vier Flaschen Wein. Sobald dieser Vorrath zu Ende gieng, mußte er verschmachten. Nun saß er da voll Schmerz und Trauer, aß jeden Tag nur ein Bißlein Brot, trank nur einen Schluck Wein, und sah doch wie der Tod immer näher rückte. Indem er so vor sich hinstarrte, sah er aus der Ecke des Gewölbes eine Schlange hervor kriechen, die sich der Leiche näherte. Und weil er dachte sie käme um daran zu nagen, zog er sein Schwert und sprach 'so lange ich lebe sollst du sie nicht anrühren,' und hieb sie in drei Stücke. Über ein Weilchen kroch eine zweite Schlange aus der Ecke hervor, als sie aber die andere todt und zerstückt liegen sah, gieng sie zurück, kam bald wieder und hatte drei grüne Blätter im Munde. Dann nahm sie die drei Stücke von der Schlange, legte sie, wie sie zusammen gehörten, und that auf jede Wunde eins von den Blättern. Alsbald fügte sich das Getrennte an einander, die Schlange regte sich und ward wieder lebendig, und beide eilten mit einander fort. Die Blätter blieben auf der Erde liegen, und dem Unglücklichen, der alles mit angesehen hatte, kam es in die Gedanken, ob nicht die wunderbare Kraft der Blätter, welche die Schlange wieder lebendig gemacht hatte, auch einem Menschen helfen konnte. Er hob also die Blätter auf und legte eins davon auf den Mund der Todten, die beiden andern auf ihre Augen. Und kaum war es geschehen, so bewegte sich das Blut in den Adern, stieg in das bleiche Angesicht und röthete es wieder. Da zog sie Athem, schlug die Augen auf und sprach 'ach, Gott, wo bin ich?' 'Du bist bei mir, liebe Frau,' antwortete er, und erzählte ihr wie alles gekommen war und er sie wieder ins Leben erweckt hatte. Dann reichte er ihr etwas Wein und Brot, und als sie wieder zu Kräften gekommen war, erhob sie sich, und sie giengen zu der Thüre, und klopften und riefen so laut daß es die Wachen hörten und dem Könige meldeten. Der König kam selbst herab und öffnete die Thüre, da fand er beide frisch und gesund, und freute sich mit ihnen daß nun alle Noth überstanden war. Die drei Schlangenblätter aber nahm der junge König mit, gab sie einem Diener und sprach 'verwahr sie mir sorgfältig, und trag sie zu jeder Zeit bei dir, wer weiß in welcher Noth sie uns noch helfen können.'

(Bild einfügen)

# 4. Pretest

(Bild einfügen)

Es war aber in der Frau, nachdem sie wieder ins Leben war erweckt worden, eine Veränderung vorgegangen: es war als ob alle Liebe zu ihrem Manne aus ihrem Herzen gewichen wäre. Und als er nach einiger Zeit eine Fahrt zu seinem alten Vater über das Meer machen wollte und sie auf ein Schiff gestiegen waren, so vergaß sie die große Liebe und Treue, die er ihr bewiesen und womit er sie vom Tode gerettet hatte, und faßte eine böse Neigung zu dem Schiffer.

# 5. Analyse und Ergebnisse

Und als der junge König einmal da lag und schlief, rief sie den Schiffer herbei, und faßte den schlafenden am Kopfe, und der Schiffer mußte ihn an den Füßen fassen, und so warfen sie ihn hinab ins Meer. Als die Schandthat vollbracht war, sprach sie zu ihm 'nun laß uns heimkehren und sagen er sei unterwegs gestorben. Ich will dich schon bei meinem Vater so herausstreichen und rühmen, daß er mich mit dir vermählt und dich zum Erben seiner Krone einsetzt.' Aber der treue Diener, der alles mit angesehen hatte, machte unbemerkt ein kleines Schifflein von dem großen los, setzte sich hinein, schiffte seinem Herrn nach, und ließ die Verräther fortfahren. Er fischte den Todten wieder auf, und mit Hilfe der drei Schlangenblätter, die er bei sich trug, und auf die Augen und den Mund legte, brachte er ihn glücklich wieder ins Leben. Sie ruderten beide aus allen Kräften Tag und Nacht, und ihr kleines Schiff flog so schnell dahin daß sie früher als das andere bei dem alten Könige anlangten. Er verwunderte sich als sie allein kommen sah und fragte was ihnen begegnet wäre. Als er die Bosheit seiner Tochter vernahm, sprach er 'ich kanns nicht glauben, daß sie so schlecht gehandelt hat, aber die Wahrheit wird bald an den Tag kommen,' und hieß beide in eine verborgene Kammer gehen und sich vor jedermann heimlich halten.

(Bild einfügen)

Bald her nach kam das große Schiff herangefahren, und die gottlose Frau erschien vor ihrem Vater mit einer betrübten Miene. Er sprach 'warum kehrst du allein zurück? wo ist dein Mann?' 'Ach, lieber Vater,' antwortete sie, 'ich komme in großer Trauer wieder heim, mein Mann ist während der Fahrt plötzlich erkrankt und gestorben, und wenn der gute Schiffer mir nicht Beistand geleistet hätte, so wäre es mir schlimm ergangen; er ist bei seinem Tode zugegen gewesen und kann euch alles erzählen.' Der König sprach 'ich will den Todten wieder lebendig machen' und öffnete die Kammer, und hieß die beiden heraus gehen. Die Frau, als sie ihren Mann erblickte, war wie vom Donner gerührt, sank auf die Knie und bat um Gnade. Der König sprach 'da ist keine Gnade, er war bereit mit dir zu, sterben und hat dir dein Leben wieder gegeben, du aber hast ihn im Schlaf umgebracht, und sollst deinen verdienten Lohn empfangen.' Da ward sie mit ihrem Helfershelfer in ein durchlöchertes Schiff gesetzt und hinaus ins Meer getrieben, wo sie bald in den Wellen versanken.

(Bild einfügen)

Jacob Grimm (1785-1863) und Wilhelm Grimm (1786-1859)

# 6. Fazit, Learning und Diskussion 

Welches LEearning ist hier die Frage?

# 7. Quellen 

# 8. Anhang mit Arbeitsaufteilung 
